### ISSUE TITLE
Resizing the window affects train speed

### ISSUE THREAD

**Issue by mpomery** [davidwengier/Trains.NET#100]
Trains started with configuration on the right. Resizing the window seemed to affect the train speeds so instead of following each other around one ended up way behind the others resulting in the trains crashing.

![image](https://user-images.githubusercontent.com/1911041/88173693-5996b180-cc66-11ea-826d-425e1fc8e36d.png)

**Comment by ScottHolden** [comment]
I'll put in a PR for a part 1 change

**Comment by ScottHolden** [comment]
#102

**Comment by mpomery** [comment]
GIF showing the issue. Purple train moves while all other trains remain stationary https://gyazo.com/d512ff1a61f3a4efb2b04e26da3895d1

**Comment by ScottHolden** [comment]
I've repo'd the issue, pushing the full fix now.

**Comment by ScottHolden** [comment]
Fully resolved in #102

**Comment by davidwengier** [comment]
This is fixed!
