### ISSUE TITLE
Hints for making things move!

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/Trains.NET#12]
Here is a quick checklist of things to consider when starting on trains. Note that this is only 1 approach, and is based off the way movement was developed for the javascript version:

- First steps:
  - [x] Render the board within a loop
  - [x] Measure time between renders
  - [x] _Optional_ Display FPS
  - [ ] _Optional_ Limit maximum frame rate
- Create & Draw:
  - [x] Set-up a way of storing all moving entities (trains) within the game, you will need one or both of the following stored on them: (Having a way to convert between these 2 is also very helpful!)
    - An absolute X & Y position of the entity within the game board (easiest to start drawing with)
    - A reference to the current cell it is on top of, and an X & Y relative to this cell (simpler for movement)
  - [x] Add code to place an entity anywhere on the board
  - [x] Add code to your 'Render' function to draw a dot/square/something simple at this location
[x] By the end of this you should be able to click and see a dot appear!
- Game Step:
  - [x] Add a 'do all the things' (game step) function that is responsible for calling update/step on each entity that will move, for now this can be parameter-less
  - [x] To start, add some very simple movement code, X++ for example, to the entity
  - [x] Add the GameStep call to the loop created in first steps
  - By the end of this you should be able to place a train/dot and see it move across the screen, with its speed tied to the frame rate.
- Delta-T
  - [ ] Modify your game loop to measure time between each game step (hint, did we do something similar earlier?)
  - [ ] Modify the GameStep function to take in a delta-t (time passed since last movement), and pass it in!
  - [ ] Modify your entities to store a velocity/speed (could be randomly set on creation? :) )
  - [ ] Using the entities velocity & delta-t, calculate the distance it should move
  - [ ] For now, just add this to X
  - By the end of this you should have dots/trains moving at a constant speed irrespective of FPS
  - [ ] _Optional_ Instead of always just passing in total delta-t, loop through passing in a semi-fixed time-step, meaning movement will always be a fixed value each evaluation of GameStep: (This is something to revisit later, gotta have accurate physics :P
    `step=0.01; t+=leftOver; while(t>step) { gameStep(step); t-= step; } leftOver = t;`
- Early helpers:
  - [x] Write a function to return distance between 2 points
  - [x] Add consts for each track type to give you the total distance of the track:
    - For a straight track, this should be easy
    - For a curved track, it will be (PI*r)/2 where r is the radius of the center of the track (CenterTrackR) which should be cellWidth/2
  - [x] Write a function that given 2 points relative to 0, returns the angle (diagrams on request)
  - [x] Write a function that given an angle and a radius, return the x,y of that point
- On the right track:
  - [x] On your train/entity, add an additional property of direction it is moving, would recommend this be stored as an angle. This is also useful for drawing your train (hint hint) 
    - [x] _Optional_ Draw your train as a box/line pointing in the correct direction
  - [x] Add a call to each cell type (or a method that takes in cell type), for a given position relative to the cell, and a distance the entity needs to move, find it's new position, and return it along side any remaining distance to travel. (no need to fill in the implementation yet!) There are 2 ways to approach this:
    - A cell knows about it's neighbors, so passes back the next cell to be called
    - A cell has no knowledge of it's neighbors, so simply returns a position outside of its self by a marginal amount, and it is the trains responsibility to grab the cell below it
  - [x] Implement horizontal track movement with the following behavior:
    - [x] If the relative y-position is within a certain range of the middle of the cell (SnapFactor), then set the Y to always be on the track. Make sure direction is a fixed horizontal angle, if it isn't coming in, then there is a bigger issue! If either of these cases are false, then the tracks aren't connected :)
    - [x] Move along X by distance, in the correct direction, passing back the new position and any remaining distance. If we travel further than the length of the piece of track, then we should follow the rules above. (need to add more detail here :P)
  - [x] Implement vertical track movement, following the rules above, keep in mind to snap direction!
  - [ ] Implement cross track movement using direction and the 2 rules above
  - [x] Implement curve track movement with the following behavior:
    - [x] Check to see if the point given is on the curve, if it isn't, then snap within SnapFactor. This can be found by calculating the angle of the point on a similar curve to the track, and then using the _angle_ and radius of the center of the track (CenterTrackR) to find the 'on track' point, then finding the distance between 2 points. This angle is used in a moment :)
    - [x] Given you are at _angle_, find the distance of track in front of you (trackLeft). (think PI/2, and the total distance of a curve you calculated before. 'in front of you' is using your direction to find which part of the curve you care about.
    - [x] Given you have trackLeft, check if it is less than the distance you need to travel, if it is, use this to find your new angle, and in turn, return your new point and 0 distance left to travel. You can also return your new angle, which is perpendicular to the angle calculated.
    - [x] If you need to move more than the tack left, find your new point, return it and remaining distance. Snap the angle to either horizontal or vertical depending on the perpendicular angle
  - At this point you should be able to write a crap ton of tests for movement. Ideally you should now have a train that; given a distance it needs to travel, will call cell's to move along, continuously, until there is no remaining distance. This gives you all of your train movement!
- The rest of the Owl
  - [ ] Draw an actual train!
  - [ ] Using everything you have above, implement carriages. You have 2 options:
    - [ ] Treat every carriage as a separate entity, move them independently (this was how the JS version was done)
    - [ ] Move backwards by X to find all points along the train. Slightly more computationally expensive, and harder to detect collisions, but means you can't "loose" carriages :P
  - [ ] Your train already has velocity, give it target velocity and acceleration (plus breaking!). Trains now speed up and slow down.

Hopefully this is of some help, more of a brain dump :)
Happy to diagram out any of the steps if needed!

**Comment by ScottHolden** [comment]
Additional thoughts (mobile so excuse formatting):

- Horizontal and vertical are the same, just with X&y swapped and direction rotated 90 degrees
- All curves are the same, just flipped on the X, y, or both, and direction adjusted accordingly
- If you had an IPoint, you could wrap it into a NormalisedPoint to pass into any of the operations above, then denormalise after it has been updated.

I think in this case the DRY'est way might be the simplest 🙂

**Comment by davidwengier** [comment]
Owls have been drawn.
