### ISSUE TITLE
IMO I think CoordsToViewPortPixels should be bool TryGetCoordsAsViewPortPixels(out x, out y) and return True if it is on screen.

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/Trains.NET#127]
![image](https://user-images.githubusercontent.com/20675893/91435934-84e66f00-e8aa-11ea-8d62-ba7fda3f7b0e.png)

**Comment by ScottHolden** [comment]
This was done!
https://github.com/davidwengier/Trains.NET/blob/master/src/Trains.NET.Rendering/PixelMapper.cs#L61

**Comment by davidwengier** [comment]
Kinda :P

But I'll allow it :)
