### ISSUE TITLE
Train movement concerns

### ISSUE THREAD

**Issue by davidwengier** [davidwengier/Trains.NET#32]
_Note: All of this is a brain-dump of thoughts that make for interesting thinking. I suspect most of these issues will come out in the wash as we slowly build up capabilities of the system_

Train positioning is an inherently pixel-based thing, as it has to happen within a cell, but, pixels are currently only the concern of the rendering layer. Train movement being in the rendering layer is just silly, obviously.

Options could be:

* make everything deal with pixels as the smallest unit (for consoles this would be one char)
    * CellSize becomes something that only the TrackLayoutRenderer (and GridRenderer) worry about, when offsetting to a cell
* have train position represented as a float from 0 to 1, which is essentially a percentage of the way through the cell

The problem with the first option is that positioning withing a cell is a tracks responsibility - it knows where it curves etc. - so how does that work if there is no formal definition of a cell? I guess there just needs to be hit-testing for tracks, but that hit-testing would have to be in the engine layer, so we need a cell concept in the engine layer after all.

The second option makes speed easy - its just the amount to increment the float each time, divided by the height of the track in cells. The problem with the second option is that positioning is not just percentage based - eg a curved track. This actually makes sense though, as positioning the train in the cell should be a track renderers responsibility anyway, as the shape of the curve is determined by it. Imagine a "straight" track that renders a chicane in the middle of itself - its still a straight track that connects Up and Down, but train positioning is not a straight line.

The interesting part here is that drawing a train is a train renderers responsibility, and it has to ask the track where to position the train, based on a distance through that comes from the train itself, so quite the convoluted coupling of objects.

**Comment by ScottHolden** [comment]
You could also represent train position as XY floats within a cell, which makes it easier to do curves. (Track length for a straight is only 1*CellSize in pixels, but (PI*CellSize)/4 on corners, so as a 0-1 would mean the train would move faster through curves).

**Comment by davidwengier** [comment]
Good point, I was oversimplifying a lot when I said it was cell size "divided by the height of the track in cells". The _real_ truth though is that even `(PI*CellSize)/4` is an oversimplification too, as it assumed a constant curve. There is no reason someone couldn't write a single track piece that looks like:

![image](https://user-images.githubusercontent.com/754264/72119093-59f4ec80-33a7-11ea-830a-4f63e50d7715.png)

So whilst having X and Y is definitely a good idea, realistically it also means that amount to increment, and angle, are both the responsibility of the track. I do like the idea of thinking of X and Y as "position within a cell" rather than "percentage through the cell" like I had it.

**Comment by ScottHolden** [comment]
Total length of that track is `2 * Cellsize + 4 * (PI*Cellsize) / 4`, `(PI*CellSize)/4` is the true actual length per every corner :)

**Comment by ScottHolden** [comment]
In that case, a cell would need to store total rows & total columns, so in reality it isn't a float between 0-1, but 0-rows & 0-columns.

**Comment by davidwengier** [comment]
I was thinking the track would just translate that to 0-1 to make the contract easier for consumers.

**Comment by ScottHolden** [comment]
Each track would need to be scale aware and adjust, as moving 0.1 in the X is the same distance as 0.4 in the Y (pixel scale)

**Comment by davidwengier** [comment]
> Hmm, I think writing for 1x1 track types to begin with will keep things simple.

See note in italics at the top :P

**Comment by ScottHolden** [comment]
Pft, i didn't read the issue, just started commenting :P
