### ISSUE TITLE
Track drawing performance investigation

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/Trains.NET#58]
Test layout:
![image](https://user-images.githubusercontent.com/20675893/81288779-aaa3fa00-90a8-11ea-86e3-7fb171da5042.png)
Share code: `1CTgScCTmCTgScCTgSc2BMTExMTExPAmJiYmJiYnsCrKrKrKrKrKrKrOBZpZpZpZpZpZpZo=`

Breakdown of drawing tracks:
![image](https://user-images.githubusercontent.com/20675893/81288936-e2ab3d00-90a8-11ea-8d0f-dfaad775c270.png)

**Comment by davidwengier** [comment]
I think we know where the issues are here.
