### ISSUE TITLE
Random ideas on different sized track pieces & efficiency

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/Trains.NET#60]
- Remove the storage of tracks within a position keyed dictionary
- Build a quadtree for locating a track in a cell (or for v1, just loop through everything)
- Store connection points for each track, so next track is just getting a value (basically turning the track into a graph)
  - This could be a sub-sampled grid, or grid + direction

Also need to consider the grid on a 2x2 item, is there grid lines in the middle of it?

**Comment by davidwengier** [comment]
I agree, and have been thinking along these lines for a while - the dictionary is essentially useless anyway. As long as each track knows where it is, its irrelevant that they be stored in a dictionary at all, it just makes for a convenient `IsTrackAt()` method.

A quadtree (whatever that is :P) versus looping, and even storing connection points, both feel like very interesting ideas that would be fun to explore, but I wonder if they're not implementation details? Perhaps the first step is to come up with a nice `ITrackLayout` API, separate from `GameBoard` (though it could implement it) and as long as there is good test coverage for those methods, we could try a few approaches.

> Also need to consider the grid on a 2x2 item, is there grid lines in the middle of it?

I don't think gridlines are "real", and in fact have been thinking about just removing them. At the moment they're on the top and left of a cell, but thats quite disingenuos.

**Comment by ScottHolden** [comment]
> I don't think gridlines are "real", and in fact have been thinking about just removing them. At the moment they're on the top and left of a cell, but that's quite disingenuous.

True, can we also settle on exactly what is a cell? :P
I was looking at something yesterday and couldn't figure out a clear answer between, `0<x<CellWidth`, `0<=x<CellWidth`, and `0<=x<=CellWidth`

**Comment by davidwengier** [comment]
I don't know the answer but I'm sure my friend `IPixelMaoper` will able to work it out! 😛

**Comment by ScottHolden** [comment]
Ehh, I feel this will work itself out in the future.
