### ISSUE TITLE
Thoughts on optimizing train path planning

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/Trains.NET#62]
Just some thoughts - rewritten to remove ego, apologies for initial snark.

An alternative approach to moving trains:

 - For each Train
   - If we are stopped (not paused), then we can claim out current track and exit early. Should only do this if we are stopped NOT if we are paused, as paused means we need to keep looking ahead to know when we can move next.
   - Adjust our speed
   - Create a dummy train
   - Move the dummy train ahead by ToMove distance, if we find the end of the track or a conflict (described below) then we should instantly stop instead of slowing down, as we are about to crash. Take note of the tracks covered, this should include the track the train starts on.
   - At this stage we can set the position of the actual train to the dummy trains position, as there was no critical move issue. The code below then determines if we need to slow down.
   - Move the dummy ahead by Look-ahead distance minus distance to move, take note of the tracks covered (don't care about the final position).
   - Taking note of tracks is done in the following way:
     - We keep a Dictionary of <Track, (Train, int)> containing the Tracks to claim, the train that claimed it, and the distance in cells the train is from the track
     - Check to see if there is a track in the current pos, if not, Pause ourselves and return early
     - When we get a track, firstly we check to see if it is already in the dictionary
       - _Key point here is that all trains should claim the track they are on with a distance of 0, allowing you to no longer need to get the movables at this position, you only ever check against the Dictionary_
       - If it isn't in the Dict, we add ourselves as the claiming train, with our numSteps in the int, and continue on
       - If it is already in there, we compare our numSteps with the int
         -  If our numSteps is higher, then we call Pause on ourselves, and return early
         - If our numSteps is lower, then we call Pause on the OTHER train (as it just lost the claim), and set ourselves as the Dictionary value/winning train.
     - If we get to the end of the look-ahead distance and don't return early, this means we have a clear path, and should call Resume() on ourselves just in case we were previously paused

At this point, our movement is done, and optionally you could clear the dictionary out if you want to re-use it for the next update.

There are some limitations to this example method, imagine we have the following scenario:

![image](https://user-images.githubusercontent.com/20675893/82625636-09c94900-9c29-11ea-8235-44e7ca8c3425.png)

In this scenario, the right cross will be claimed by Train 1, even though after Train 2 is processed it will be slowing down. In an ideal scenario, Train 3 would have priority over Train 1 as when Train 1 slows down, Train 3 will hit there first.

The only way to resolve this is to change to breadth first, which can still be done in a similar way, but instead of moving each train it's entire distance at a time, we move them cell by cell, which is again another approach to take.

**Comment by chrisfowles** [comment]
> Anyway, you could do an entire PHD on Train based conflict resolution, but this should be a good starting point to stop trains colliding!

... so here's a start on it.

**Comment by ScottHolden** [comment]
And having a debug layer show the information above would be sweet (saves the powerpoint drawing) :P

**Comment by davidwengier** [comment]
> At the moment for each train you loop through all the movement steps 3 times

I feel personally attacked. I acknowledge the current code needs cleaning up, and is terrible. It's called Technical Debt, look it up :P

> I wanted to put some fancy Big-O here, but couldn't be bothered.

Don't you just love Big-O. Your suggestion is O(N), my current code is O(N), and if I ran my current code 20 more times that would be O(N)!

**Comment by ScottHolden** [comment]
> I feel personally attacked. I acknowledge the current code needs cleaning up, and is terrible. It's called Technical Debt, look it up :P

Ok then! Closing the issue.

**Comment by ScottHolden** [comment]
Had some fun playing round :)

![PoliteTrains](https://user-images.githubusercontent.com/20675893/82748147-01b50900-9de3-11ea-96cd-967a2e3ecb4b.gif)

**Comment by davidwengier** [comment]
Your PR was merged so I'm gonna close this.
