### ISSUE TITLE
Hitbox renderer should just colour taken tracks

### ISSUE THREAD

**Issue by davidwengier** [davidwengier/Trains.NET#67]
At the moment the hitbox renderer (TrainLookaheadRenderer) calls GetNextSteps() and colours in the results, which means it doesn't keep up with the changes to the collision detection code as we write it. A better idea is to expose the GameBoard's dictionary of track leases (WE SHOULD TOTALLY CALL THEM LEASES!!!) and just have it colour those, and it can still colour them based on the train that holds the lease.

That way it will do the look behind, or will cater for future carriages, etc.

**Comment by ScottHolden** [comment]
Love the name leases!
