### ISSUE TITLE
Fix DI for classes that implement multiple interfaces

### ISSUE THREAD

**Issue by davidwengier** [davidwengier/Trains.NET#70]
ITool and IDraggableTool, and ILayerRenderer and ICacheableLayerRenderer should be sorted so you don't need to express both interfaces.

**Comment by davidwengier** [comment]
Yeah this just works ¯\_(ツ)_/¯

**Comment by ScottHolden** [comment]
Note for future Dave: If a class implements 2 interfaces, it will be registered as 2 singletons aka 2 instances of it will exist (one for each interface).
If you expect resolving either interface to return the same instance, you may run into trouble :P

**Comment by davidwengier** [comment]
I should get off at singletons... But I like singletons! Actually I want things to be more single!

**Comment by davidwengier** [comment]
New DI fixed all issues!!!

(I think?)
