### ISSUE TITLE
Some way to render custom cursors for tools

### ISSUE THREAD

**Issue by mortizzle** [davidwengier/Trains.NET#83]
I was thinking for the Terrain tool it would be cool to have a circle cursor to show the circle of interaction, which could be made bigger/smaller or the magnitude or gradient of terrain manipulation changed. A track pointer for laying tracks would be pretty dope too.

**Comment by davidwengier** [comment]
Implement ICustomCursor or IPreviewableTool in your ITool and you'll be able to add magic
/giphy magic
