### ISSUE TITLE
Cursor disappears?

### ISSUE THREAD

**Issue by Zireael07** [davidwengier/Trains.NET#87]
On Linux Manjaro, Brave browser, once my cursor is in the gameplay area, it's no longer visible.

**Comment by ScottHolden** [comment]
Is this for Trains.Net or the original web version? What version of Brave are you using?

**Comment by Zireael07** [comment]
Wersja 1.7.90 Chromium: 80.0.3987.163 (Official Build) unknown (64-bit)

Curiously, on a second run, it worked. Re: version, whichever it is at https://jamesformica.github.io/trains/

**Comment by ScottHolden** [comment]
Looks like a race condition, managed to replicate on chrome, but displays an unknown character 'block' instead of no cursor.

**Comment by davidwengier** [comment]
I get the unknown character thing on chrome all the time, I suspect race condition too, where the browser hasn't downloaded the cursor image.

Glad you got it working.

**Comment by ScottHolden** [comment]
This repo is for the .NET version of trains, if you'd like to dig into the version you linked above, see:
https://github.com/jamesformica/trains
